src/app/destinations/models.py
import datetime

from app import db


UsersDestinations = db.Table('usersdestinations',
    db.Column('user_id', db.Integer, db.ForeignKey('users.id')),
    db.Column('destination_id', db.Integer, db.ForeignKey('destinations.id'))
)


class Destination(db.Model):
    __tablename__ = 'destinations'

    id = db.Column(db.Integer, primary_key=True)
    city = db.Column(db.String, nullable=False)
    country = db.Column(db.String, nullable=False)
    rating = db.Column(db.Integer)
    order = db.Column(db.Integer)

    photo = db.Column(db.String)

    description = db.Column(db.Text)

    is_completed = db.Column(db.Boolean, nullable=False, default=False)

    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow,
                           onupdate=datetime.datetime.utcnow)
    created_by = db.Column(db.String)
    updated_by = db.Column(db.String)

    comments = db.relationship('Comment', backref='destination',
                               order_by="desc(Comment.created_at)")
    users = db.relationship('User', secondary=UsersDestinations,
                            backref=db.backref('destinations'))


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    destination_id = db.Column(db.Integer, db.ForeignKey('destinations.id'))
    text = db.Column(db.Text)

    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.datetime.utcnow,
                           onupdate=datetime.datetime.utcnow)
    created_by = db.Column(db.String)
    updated_by = db.Column(db.String)

src/app/destinations/forms.py
import pycountry
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import (
    HiddenField,
    SelectField,
    SelectMultipleField,
    StringField,
    TextAreaField,
)
from wtforms.validators import required, url

from app import db
from app.auth.models import User


def get_travelers_choices():
    return db.session.query(User).filter(User.id != current_user.id)


class DestinationForm(FlaskForm):
    country = SelectField(
        u'Country',
        validators=[required()],
        choices=[(country.name, country.name)
                 for country in pycountry.countries]
    )
    city = StringField(u'City', validators=[required()])

    photo = StringField(u'Photo url', validators=[url()])
    description = TextAreaField(u'Description')
    traveling_with = SelectMultipleField(
        u'I will travel with',
        coerce=int,
        choices=[]
    )


class CommentForm(FlaskForm):
    destination_id = HiddenField()
    text = TextAreaField(u'Comment', validators=[required()])

src/app/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)

flask_bcrypt = Bcrypt(app)

from app.auth.views import auth
from app.auth.models import User
app.register_blueprint(auth)

from app.destinations.views import destinations
app.register_blueprint(destinations)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

src/app/destinations/views.py
from flask import Blueprint, request, redirect, url_for, render_template
from flask_login import login_required, current_user

from app import db
from app.auth.models import User
from app.destinations.models import Destination, Comment
from app.destinations.forms import CommentForm, DestinationForm

destinations = Blueprint('destinations', __name__)


@destinations.route('/')
@login_required
def records():
    dests = current_user.destinations
    if request.args.get('all') is None:
        dests = filter(lambda x: not x.is_completed, dests)
    return render_template(
        'destinations/records.html',
        dests=dests,
        current_user=current_user,
    )


@destinations.route('/destinations/<int:destination_id>')
@login_required
def show(destination_id):
    dest = Destination.query.filter_by(id=destination_id).filter(
        Destination.users.any(id=current_user.id)
    ).first_or_404()
    form = CommentForm(destination_id=dest.id)
    return render_template('destinations/show.html', dest=dest, form=form)


@destinations.route('/destinations/delete/<int:destination_id>')
@login_required
def delete(destination_id):
    dest = Destination.query.filter_by(id=destination_id).filter(
        Destination.users.any(id=current_user.id)
    ).first_or_404()

    db.session.delete(dest)
    db.session.commit()

    return redirect(url_for('destinations.records'))


@destinations.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = DestinationForm()
    travel_with = db.session.query(User).filter(
        User.id != current_user.id
    )
    form.traveling_with.choices = [(user.id, user.name) for user in travel_with]

    if form.validate_on_submit():
        destination = Destination(
            created_by=current_user.name,
            updated_by=current_user.name,
        )
        form.populate_obj(destination)

        destination.users.append(current_user)

        if form.traveling_with.data:
            travelers = db.session.query(User).filter(User.id.in_(
                form.traveling_with.data
            ))
            destination.users.extend(travelers)

        db.session.add(destination)
        db.session.commit()

        return redirect(url_for('destinations.records'))

    return render_template(
        'destinations/add.html',
        current_user=current_user,
        form=form,
    )


@destinations.route('/destinations/edit/<int:destination_id>', methods=['GET', 'POST'])
@login_required
def edit(destination_id):
    destination = Destination.query.filter_by(id=destination_id).filter(
        Destination.users.any(id=current_user.id)
    ).first_or_404()

    form = DestinationForm(obj=destination)
    travel_with = db.session.query(User).filter(
        User.id != current_user.id
    )
    form.traveling_with.choices = [(user.id, user.name) for user in travel_with]

    if form.validate_on_submit():
        form.populate_obj(destination)
        destination.updated_by = current_user.name

        destination.users.append(current_user)

        if form.traveling_with.data:
            travelers = db.session.query(User).filter(User.id.in_(
                form.traveling_with.data
            ))
            destination.users.extend(travelers)

        db.session.add(destination)
        db.session.commit()

        return redirect(url_for('destinations.show', destination_id=destination.id))

    return render_template(
        'destinations/edit.html',
        current_user=current_user,
        form=form,
    )


@destinations.route('/destinations/mark_completed/<int:destination_id>', methods=['GET'])
@login_required
def mark_completed(destination_id):
    destination = Destination.query.filter_by(id=destination_id).filter(
        Destination.users.any(id=current_user.id)
    ).first_or_404()
    destination.is_completed = True
    db.session.add(destination)
    db.session.commit()

    return redirect(url_for('destinations.records'))


@destinations.route('/comments/add', methods=['POST'])
@login_required
def comment_add():
    form = CommentForm()

    if form.validate_on_submit():
        comment = Comment(
            created_by=current_user.name,
            updated_by=current_user.name,
        )

        form.populate_obj(comment)
        db.session.add(comment)
        db.session.commit()

        return redirect(url_for(
            'destinations.show',
            destination_id=request.form['destination_id']
        ))

src/app/templates/destinations/add.html
{% extends "layout.html" %}
{% block body %}
<form action="" method=post>
    <h2>So, you are going to:</h2>
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.country.label }}
        {{ form.country(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.city.label }}
        {{ form.city(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.photo.label }}
        {{ form.photo(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.traveling_with.label }}
        {{ form.traveling_with(class_="form-control") }}
    </div>

    <button type="submit" class="btn btn-default">Add Destination</button>
</form>
{% endblock %}

src/app/templates/destinations/edit.html
{% extends "layout.html" %}
{% block body %}
<form action="" method=post>
    <h2>Edit destination:</h2>
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.country.label }}
        {{ form.country(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.city.label }}
        {{ form.city(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.photo.label }}
        {{ form.photo(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class_="form-control") }}
    </div>
    <div class="form-group">
        {{ form.traveling_with.label }}
        {{ form.traveling_with(class_="form-control") }}
    </div>

    <button type="submit" class="btn btn-default">Edit</button>
</form>
{% endblock %}

src/app/templates/destinations/records.html
{% extends "layout.html" %}
{% block body %}
{% if dests %}
<h2>Your destinations:</h2>
<ul>
{% for dest in dests %}
    <li>
        <h3>
            <a href="{{ url_for('destinations.show', destination_id=dest.id) }}">
                {{ dest.city }}, {{ dest.country }}
            </a>{% if dest.is_completed %} [Completed]{% endif %}
        </h3>
        <div>
            {% if not dest.is_completed %}
                <a href="{{ url_for('destinations.mark_completed', destination_id=dest.id) }}"
                class="btn btn-success btn-xs">
                    Mark Completed
                </a>
            {% endif %}
            <a href="{{ url_for('destinations.edit', destination_id=dest.id) }}"
            class="btn btn-default btn-xs">
                Edit
            </a>
            <a href="{{ url_for('destinations.delete', destination_id=dest.id) }}"
            class="btn btn-danger btn-xs">
                Delete
            </a>
        </div>
    </li>
{% endfor %}
</ul>

{% else %}
    <h1 class="text-center">You have no destinations yet! Go ahead and add one!</h1>
{% endif %}
<p class="text-center">
    <a class="btn btn-lg btn-success" href="{{ url_for('destinations.add') }}" role="button">Add Destination</a>
</p>

{% endblock %}

src/app/templates/destinations/show.html
{% extends "layout.html" %}
{% block body %}
<a href="{{url_for('destinations.records') }}"><< To destinations list</a>
<div class="row">
    <div class="col-md-6">
        <h1>{{ dest.city }}, {{dest.country }}{% if dest.is_completed %} [Completed]{% endif %}</h1>


        <p>{{ dest.description }}</p>

        <h3>Travelers:</h3>
        <ul>
            {% for traveler in dest.users %}
            <li>{{ traveler.name }}</li>
            {% endfor %}
        </ul>

        {% if not dest.is_completed %}
            <a href="{{ url_for('destinations.mark_completed', destination_id=dest.id) }}"
            class="btn btn-success btn-xs">
                Mark Completed
            </a>
        {% endif %}
        <a href="{{ url_for('destinations.edit', destination_id=dest.id) }}"
        class="btn btn-default btn-xs">
            Edit
        </a>
        <a href="{{ url_for('destinations.delete', destination_id=dest.id) }}"
        class="btn btn-danger btn-xs">
            Delete
        </a>
    </div>
    <img src="{{ dest.photo }}" class="col-md-6"/>
</div>

<div class="row">
    <h2>Comments:</h2>
    <form action="{{ url_for('destinations.comment_add') }}" method="post">
        {{ form.csrf_token }}
        {{ form.destination_id() }}
        <div class="form-group">
            {{ form.text(class_="form-control") }}
        </div>
        <button type="submit" class="btn btn-default">Add comment</button>
    </form>
</div>
<div class="row" style="margin-top: 20px">
{% for comment in dest.comments %}
    <div class="col-md-12">
    <blockquote>
        <small><strong>{{ comment.created_by }}</strong> {{ comment.created_at.strftime('%H:%M:%S %Y-%m-%d') }}</small>
        <p>{{ comment.text }}</p>
    </blockquote>
    </div>
{% endfor %}
</div>


{% endblock %}